#!/usr/bin/env bash
set -euo pipefail

DAILY_TEAM_ROOT="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OPENAI_CODEX_QUICK_PRIMARY="${OPENAI_CODEX_QUICK_PRIMARY:-gpt-5.6-luna}"
OPENAI_CODEX_QUICK_FALLBACK="${OPENAI_CODEX_QUICK_FALLBACK:-gpt-5.6-terra}"
OPENAI_CODEX_STANDARD_PRIMARY="${OPENAI_CODEX_STANDARD_PRIMARY:-gpt-5.6-terra}"
OPENAI_CODEX_STANDARD_FALLBACK="${OPENAI_CODEX_STANDARD_FALLBACK:-gpt-5.6-sol}"
OPENAI_CODEX_COMPLEX_PRIMARY="${OPENAI_CODEX_COMPLEX_PRIMARY:-gpt-5.6-sol}"
OPENAI_CODEX_COMPLEX_FALLBACK="${OPENAI_CODEX_COMPLEX_FALLBACK:-gpt-5.6-terra}"
OPENAI_CODEX_REASONING_EFFORT="${OPENAI_CODEX_REASONING_EFFORT:-low}"
OPENAI_CODEX_COMPACT_TOKEN_LIMIT="${OPENAI_CODEX_COMPACT_TOKEN_LIMIT:-32000}"
OPENAI_TOKEN_WARN_ORCHESTRATOR_UNCACHED="${OPENAI_TOKEN_WARN_ORCHESTRATOR_UNCACHED:-12000}"
OPENAI_TOKEN_WARN_WRAPPER_UNCACHED="${OPENAI_TOKEN_WARN_WRAPPER_UNCACHED:-3000}"
OPENAI_TOKEN_WARN_CODEX_UNCACHED="${OPENAI_TOKEN_WARN_CODEX_UNCACHED:-24000}"
OPENAI_TOKEN_WARN_AGENT_UNCACHED="${OPENAI_TOKEN_WARN_AGENT_UNCACHED:-10000}"
OPENAI_DAILY_PROFILE=1
OPENAI_DAILY_ALLOWED_PROVIDER=openai
export OPENAI_DAILY_PROFILE OPENAI_DAILY_ALLOWED_PROVIDER

# Reuse the OpenAI runtime policy while keeping DAILY state under its own sandbox.
source "$DAILY_TEAM_ROOT/../openai/runtime-env.sh"
export OPENAI_DAILY_PROFILE OPENAI_DAILY_ALLOWED_PROVIDER
