#!/usr/bin/env bash
set -euo pipefail

TEAM_ROOT="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$TEAM_ROOT/../../shared/runtime-env/github-token.sh"

OPENAI_TEAM_ROOT="$TEAM_ROOT"
OPENAI_TEAM_STATE_ROOT="${SANDBOX:?SANDBOX must be set}/state/team"
OPENAI_DEPENDENCY_ROOT="${OPENAI_DEPENDENCY_ROOT:-${OPENCODE_TEAM_DEPENDENCY_ROOT:-$(cd "$SANDBOX/../dependencies" && pwd)}/openai}"
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
OPENAI_CODEX_MODEL="${OPENAI_CODEX_MODEL:-}"
OPENAI_CODEX_QUICK_PRIMARY="${OPENAI_CODEX_QUICK_PRIMARY:-gpt-5.3-codex-spark}"
OPENAI_CODEX_QUICK_FALLBACK="${OPENAI_CODEX_QUICK_FALLBACK:-gpt-5.6-terra}"
OPENAI_CODEX_STANDARD_PRIMARY="${OPENAI_CODEX_STANDARD_PRIMARY:-gpt-5.6-terra}"
OPENAI_CODEX_STANDARD_FALLBACK="${OPENAI_CODEX_STANDARD_FALLBACK:-gpt-5.6-sol}"
OPENAI_CODEX_COMPLEX_PRIMARY="${OPENAI_CODEX_COMPLEX_PRIMARY:-gpt-5.6-sol}"
OPENAI_CODEX_COMPLEX_FALLBACK="${OPENAI_CODEX_COMPLEX_FALLBACK:-gpt-5.6-terra}"
OPENAI_CODEX_REASONING_EFFORT="${OPENAI_CODEX_REASONING_EFFORT:-low}"
OPENAI_CODEX_COMPACT_TOKEN_LIMIT="${OPENAI_CODEX_COMPACT_TOKEN_LIMIT:-60000}"
CODEX_CLI_LOG_DIR="$SANDBOX/logs/codex"
OPENAI_WORK_PACKET_RETENTION_DAYS="${OPENAI_WORK_PACKET_RETENTION_DAYS:-7}"
OPENAI_WORK_PACKET_LOCK_STALE_MS="${OPENAI_WORK_PACKET_LOCK_STALE_MS:-30000}"
OPENAI_WORK_PACKET_LOCK_WAIT_MS="${OPENAI_WORK_PACKET_LOCK_WAIT_MS:-5000}"
OPENAI_TASK_LEASE_MS="${OPENAI_TASK_LEASE_MS:-1200000}"
OPENAI_TOKEN_BUDGET_MODE="${OPENAI_TOKEN_BUDGET_MODE:-observe}"
OPENAI_TOKEN_WARN_ORCHESTRATOR_UNCACHED="${OPENAI_TOKEN_WARN_ORCHESTRATOR_UNCACHED:-50000}"
OPENAI_TOKEN_WARN_WRAPPER_UNCACHED="${OPENAI_TOKEN_WARN_WRAPPER_UNCACHED:-5000}"
OPENAI_TOKEN_WARN_CODEX_UNCACHED="${OPENAI_TOKEN_WARN_CODEX_UNCACHED:-30000}"
OPENAI_TOKEN_WARN_AGENT_UNCACHED="${OPENAI_TOKEN_WARN_AGENT_UNCACHED:-30000}"

case "$OPENAI_CODEX_REASONING_EFFORT" in
  minimal|low|medium|high|xhigh) ;;
  *) printf '%s\n' "OPENAI_CODEX_REASONING_EFFORT must be one of: minimal, low, medium, high, xhigh" >&2; exit 2 ;;
esac
case "${OPENAI_CODEX_PROFILE:-}" in
  ''|quick|standard|complex) ;;
  *) printf '%s\n' "OPENAI_CODEX_PROFILE must be one of: quick, standard, complex" >&2; exit 2 ;;
esac
for model_var in OPENAI_CODEX_MODEL OPENAI_CODEX_FALLBACK_MODEL OPENAI_CODEX_QUICK_PRIMARY OPENAI_CODEX_QUICK_FALLBACK OPENAI_CODEX_STANDARD_PRIMARY OPENAI_CODEX_STANDARD_FALLBACK OPENAI_CODEX_COMPLEX_PRIMARY OPENAI_CODEX_COMPLEX_FALLBACK; do
  model_value=${!model_var:-}
  if [ "$model_var" != OPENAI_CODEX_MODEL ] && [ "$model_var" != OPENAI_CODEX_FALLBACK_MODEL ] && [ -z "$model_value" ]; then
    printf '%s\n' "$model_var must not be empty" >&2
    exit 2
  fi
  if [ -n "$model_value" ] && ! [[ "$model_value" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]]; then
    printf '%s\n' "$model_var must be a nonempty model name" >&2
    exit 2
  fi
done
case "$OPENAI_CODEX_COMPACT_TOKEN_LIMIT" in
  ''|*[!0-9]*|0|0[0-9]*) printf '%s\n' "OPENAI_CODEX_COMPACT_TOKEN_LIMIT must be a positive integer" >&2; exit 2 ;;
esac

mkdir -p "$OPENAI_TEAM_STATE_ROOT" "$CODEX_CLI_LOG_DIR"
case "$OPENAI_WORK_PACKET_RETENTION_DAYS" in ''|*[!0-9]*) printf '%s\n' "OPENAI_WORK_PACKET_RETENTION_DAYS must be a non-negative integer" >&2; exit 2;; esac
case "$OPENAI_WORK_PACKET_LOCK_STALE_MS,$OPENAI_WORK_PACKET_LOCK_WAIT_MS" in *[!0-9,]*|,*) printf '%s\n' "work packet lock timing must use non-negative integer milliseconds" >&2; exit 2;; esac
case "$OPENAI_TASK_LEASE_MS" in ''|*[!0-9]*) printf '%s\n' "OPENAI_TASK_LEASE_MS must be an integer milliseconds value" >&2; exit 2;; esac
if [ "$OPENAI_TASK_LEASE_MS" -lt 1000 ] || [ "$OPENAI_TASK_LEASE_MS" -gt 3600000 ]; then
  printf '%s\n' "OPENAI_TASK_LEASE_MS must be between 1000 and 3600000 milliseconds" >&2
  exit 2
fi
[ "$OPENAI_TOKEN_BUDGET_MODE" = observe ] || { printf '%s\n' "OPENAI_TOKEN_BUDGET_MODE must be: observe" >&2; exit 2; }
case "$OPENAI_TOKEN_WARN_ORCHESTRATOR_UNCACHED,$OPENAI_TOKEN_WARN_WRAPPER_UNCACHED,$OPENAI_TOKEN_WARN_CODEX_UNCACHED,$OPENAI_TOKEN_WARN_AGENT_UNCACHED" in
  *[!0-9,]*|*,,*|,*|*,) printf '%s\n' "OpenAI token warning thresholds must be non-negative integers" >&2; exit 2;;
esac

export OPENAI_TEAM_ROOT OPENAI_TEAM_STATE_ROOT OPENAI_DEPENDENCY_ROOT OPENAI_CODEX_MODEL OPENAI_CODEX_FALLBACK_MODEL OPENAI_CODEX_PROFILE
export OPENAI_CODEX_QUICK_PRIMARY OPENAI_CODEX_QUICK_FALLBACK OPENAI_CODEX_STANDARD_PRIMARY OPENAI_CODEX_STANDARD_FALLBACK
export OPENAI_CODEX_COMPLEX_PRIMARY OPENAI_CODEX_COMPLEX_FALLBACK OPENAI_CODEX_REASONING_EFFORT OPENAI_CODEX_COMPACT_TOKEN_LIMIT
export CODEX_HOME CODEX_CLI_LOG_DIR OPENAI_WORK_PACKET_RETENTION_DAYS OPENAI_WORK_PACKET_LOCK_STALE_MS OPENAI_WORK_PACKET_LOCK_WAIT_MS
export OPENAI_TASK_LEASE_MS OPENAI_TOKEN_BUDGET_MODE OPENAI_TOKEN_WARN_ORCHESTRATOR_UNCACHED OPENAI_TOKEN_WARN_WRAPPER_UNCACHED
export OPENAI_TOKEN_WARN_CODEX_UNCACHED OPENAI_TOKEN_WARN_AGENT_UNCACHED
export OMO_DISABLE_POSTHOG=1 OMO_SEND_ANONYMOUS_TELEMETRY=0
